language: python
python:
  - "2.6"
  - "2.7"
env:
  - DJANGO=1.4
install:
  - pip install -q Django==$DJANGO --use-mirrors
  - pip install pep8 --use-mirrors
  - pip install https://github.com/dcramer/pyflakes/tarball/master
  - pip install coverage
  - pip install django_coverage
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225,E261,W191,E101 ."
  - pyflakes -x W .
script:
  - python setup.py django_coverage